services:
  - type: web
    name: shl-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: MILVUS_DB
        value: "data/milvus.db"
